# Site settings
title: Daily Bible Reading Plan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://redeemerth.github.io/daily-bible-reading-plan/" # the base hostname & protocol for your site

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

# Build settings
markdown: kramdown
